##all:
##	gcc -Wall main.c -o main `pkg-config --cflags gtk+-2.0` `pkg-config --libs gtk+-2.0`
benoit:
	gcc -Wall test.c -o menu `pkg-config --cflags gtk+-2.0` `pkg-config --libs gtk+-2.0`
toto:
	gcc -Wall new.c -o new `pkg-config --cflags gtk+-2.0` `pkg-config --libs gtk+-2.0`




## Simple SDL mini code
