all:
	gcc -Wall main.c -o main `pkg-config --cflags gtk+-2.0` `pkg-config --libs gtk+-2.0`
benoit:
	gcc -Wall menu.c -o menu `pkg-config --cflags gtk+-2.0` `pkg-config --libs gtk+-2.0`

toto:
	gcc -Wall testemenu.c -o hmenu `pkg-config --cflags gtk+-2.0` `pkg-config --libs gtk+-2.0`
